### ISSUE TITLE
No issue, just a list for copy & paste where smooth scrolling works like it should

### ISSUE THREAD

**Issue by scorpion421** [igvk/LogiOptionsPlus-InMemoryPatching#1]
logioptionsplus.exe
winword.exe
telegram.exe
; Steam - it's not steam.exe, it's the webhelper.exe
steamwebhelper.exe
discord.exe
vivaldi.exe
Bitwarden.exe
Signal.exe
PowerToys.Settings.exe
SystemSettings.exe
Adguard.exe
AdGuardVpn.exe
TreeSize.exe

You, Sir, saved my sanity. 4 years of ranting and arguing with worthless L-support and me stating, it's hardcoded, and they should leave it to the users where it's working or not. Like: Logitech Options > Add app > grant smooth scrolling. But nope, not happening. Just ignorance.

**Comment by igvk** [comment]
I'm glad I was able to help! 
Yes, Logitech should have allowed for users to choose smooth scrolling apps

**Comment by paul-van-cotthem** [comment]
@igvk I would also like to express my gratitude to you for your excellent extension of smooth scrolling on Logitech Options+.

**Comment by igvk** [comment]
[scorpion421](https://github.com/scorpion421), I have incorporated most of the entries to sample apps list in source tree.

**Comment by igvk** [comment]
[paul-van-cotthem](https://github.com/paul-van-cotthem), I hope it helps make the most of using the wheel of this mouse in other applications.
